# Generated by Django 3.2.7 on 2021-09-23 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MultiSearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newuser',
            options={'verbose_name': 'NewUser', 'verbose_name_plural': 'NewUsers'},
        ),
    ]
