# Generated by Django 3.2.7 on 2021-09-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiSearch', '0003_tutorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
