# Generated by Django 3.2.7 on 2021-09-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultiSearch', '0004_auto_20210924_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
