# Generated by Django 3.2.7 on 2021-09-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MultiSearch', '0005_book_chapter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': 'Chapter', 'verbose_name_plural': 'Chapters'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='tutorial',
            options={'verbose_name': 'Tutorial', 'verbose_name_plural': 'Tutorials'},
        ),
    ]
